# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-app
  template:
    metadata:
      labels:
        app: webapp-app
    spec:
      containers:
        - name: webapp-container
          image: public.ecr.aws/t2e6o6l2/flaskapp:latest 
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
          ports:
            - containerPort: 80

---
# Service - nodePort
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp-app
spec:
  selector:
    app: webapp-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
    protocol: TCP
    name: http