# Service - nodeport
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: webapp-app
spec:
  selector:
    app: webapp-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080