---
- name: Microk8s installation
  block:
    - name: Install Microk8s from snap
      snap:
        name: microk8s
        classic: yes
        channel: "1.19"

      # sudo usermod -a -G microk8s ubuntu
    - name: Add ubuntu to microk8s user group
      user:
        name: ubuntu
        group: microk8s
        append: yes

      # sudo usermod -a -G microk8s jenkins
    - name: Add jenkins to microk8s user group
      user:
        name: jenkins
        group: microk8s
        append: yes

    - name: create the .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory

    - name: chown the .kube to ubuntu
      file:
        path: /home/ubuntu/.kube
        owner: ubuntu
        group: ubuntu

    - name: chown the .kube for jenkins
      file:
        path: /home/ubuntu/.kube
        owner: jenkins
        group: jenkins

    - name: Check status
      command: microk8s status --wait-ready

    - name: Enable dns
      command: microk8s enable dns

    - name: add alias 'microk8s kubectl' -> 'kubectl'
      copy:
        dest: "/home/ubuntu/.bash_aliases"
        content: |
          alias kubectl='microk8s kubectl'
