---
- name: Install prerequisites
  block:
    - name: Upgrade all packages
      apt:
        name: '*'
        state: latest

    - name: Ensure git is at the latest version
      apt: 
        name: git
        state: latest

    - name: Ensure apache2 is uninstalled
      apt:
        name: apache2
        state: absent

    - name: Disable swap
      command: swapoff -a
