---
- name: Install prerequisites
  block:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Ensure git is at the latest version
      yum: 
        name: git
        state: latest

    - name: Ensure pip is at the latest version
      yum:
        name: python-pip
        state: latest
