
---
- name: Run Jenkins Docker Image
  block:
    # sudo usermod -aG jenkins
    - name: add jenkins-user to docker group
      user:
        name: jenkins
        group: docker
        append: yes

    - name: Create a volume for storing Jenkins data
      docker_volume:
        name: MyVolume

    - name: Run the Jenkins image
      docker_container:
        name: MyJenkins
        image: jenkins/jenkins:lts
        ports:
          - "9090:8080"
          - "50000:50000"
        volumes: MyVolume
        state: started
        recreate: yes